### PR TITLE
Updated detailed view results and css adjustments

### LINKED ISSUE #45: Adding the comments for the detailed view of results for the instructor view.
Added the comment column in the table of the detailed view, in order to make the results more accurate. In addition, some css adjustments were also made for better and clean view.

### PR DESCRIPTION
**Pull request by khujista-01**
This PR introduces a comment box to the peer assessment detailed view table and includes CSS adjustments to improve the user interface. The comment box allows the instructor to read any additional comment left by a peer for their teammate, while the CSS changes enhance the visual structure of team and assessor details, making the layout cleaner and more organized.

Changes Made: 
- Comment Box Integration:
1. Added a comments column to the peer assessment table, allowing assessors to leave detailed feedback on each team member.
2. Updated the frontend to display the comments associated with each peer assessment entry in the summary table.
CSS Enhancements:
3. Styled the team name and assessor ID sections by placing them in clearly defined boxes for better readability.
4. Updated table styles for consistent alignment and spacing between cells.
5. Added background colors, borders, and padding to the team/assessor sections to visually separate key information.
Improved the layout and spacing of each assessment row to accommodate the new comment section without overcrowding.
This PR closes #45 .

### CODE REVIEW

**Review by flyingbearxx — APPROVED** [review]
Reviewed & Approved

**Review by yas176 — APPROVED** [review]
the conflict resolved. Approved by Yasmeen

**Review by raghdaelkei — APPROVED** [review]
good

**Review by anarostam — APPROVED** [review]
All the test pass

**Pull request merged**
